export const APIS = {
  SIGNUP: 'signup',
  LOGIN: 'login',
  CONTACT_US: 'submit_contact_request',
  SEND_OTP: 'send_otp',
  VERIFY_OTP: 'verify_otp',
  RESET_PASSWORD: 'reset_password',
  UPDATE_PASSWORD: 'updatePassword',
  DELETE_ACCOUNT: 'delete_account',
  UPDATE_PROFILE: 'update_profile',
  GET_PROFILE: 'userProfile',
  GET_JOBS: 'get_my_jobs',
  JOB_DETAIL: 'get_job_details',
  GET_NOTIFICATIONS: 'get_notifications',
  SUBMIT_QUESTIONNAIRE: 'submit_measuring_questionare',
  START_FITTING: 'start_fitting',
  uploadFile: 'uploadFile',
  DELETE_IMAGE: 'delete_measuring_questionare_image',
};
export default APIS;
